# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/OdeiCastresana"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "goodreads"
name = "Goodreads"
url = "https://www.goodreads.com/user/show/163462162-odei"

[social.params]
icon = "brand-goodreads"

[[social]]
identifier = "linkedin"
name = "linkedin"
url = "https://www.linkedin.com/in/hodei-castresana"

[social.params]
icon = "brand-linkedin"

